### ISSUE TITLE
bug(stac): CDSE reads blocked by pyramids#983 (CloudConfig custom endpoint lost on large reads)

### ISSUE THREAD

**Issue by MAfarrag** [serapeum-org/earthlens#1029]
## Summary

The CDSE STAC endpoint cannot complete a mosaic/download through the backend, even with valid credentials, because
of an upstream pyramids bug. `TestCdseE2E` is `xfail`ed pending that fix (PR #1028); this issue tracks removing the
`xfail` once pyramids ships the fix.

## What works
- The `CDSE_S3_ACCESS_KEY` / `CDSE_S3_SECRET_KEY` repo secrets are set and **valid** — a direct
  `gdal.Open` + `ReadAsArray` of a real Sentinel-2 `B04_10m` asset from `s3://eodata/...` succeeds
  (10980×10980).
- The CDSE test's asset name was also wrong (`B04` vs CDSE's `B04_10m`); fixed in #1028.

## What's blocked
A **large** CDSE read through `EarthLens(...).download()` (the mosaic path) fails: GDAL is sent to **real AWS**
(`eodata.s3.<region>.amazonaws.com` → `403`) instead of the CDSE host `eodata.dataspace.copernicus.eu`.

Root cause (upstream): **serapeum-org/pyramids#983** — `pyramids.base.remote.CloudConfig` applies the custom
`AWS_S3_ENDPOINT` **thread-locally** (`gdal.config_options`), which GDAL's VSICurl worker threads (multi-range
fetch of a large raster) do **not** inherit. So the endpoint is lost on large reads against a non-AWS S3-compatible
store like CDSE. Applying the identical config **globally** (`gdal.SetConfigOption`) reads fine — that's the proof
it's the config-application mechanism, not the credentials or the data. (AWS-hosted anonymous endpoints such as
DEAfrica are unaffected because their fallback host *is* real AWS.)

A second pyramids bug (`merge_rasters` calling `.FlushCache()` on an unguarded `gdal.Translate` result) masks this
as an opaque `AttributeError: 'NoneType' object has no attribute 'FlushCache'`. Both are covered in pyramids#983.

## Exit criteria
- [ ] pyramids#983 fixed and the floor bumped in earthlens.
- [ ] Remove `@pytest.mark.xfail` from `TestCdseE2E` (added in #1028) and confirm the CDSE e2e lane goes green.

## Related
- serapeum-org/pyramids#983 — the upstream fix
- #1028 — the PR that marker-gates the CDSE/usgs e2e and xfails this pending #983
- #1018 — STAC e2e audit (CDSE was one of the never-run endpoints)

## Note (separate, tracked here for visibility)
`TestUsgsLandsatE2E` is also `xfail`ed in #1028 — for a different reason: no AWS requester-pays credentials are
provisioned as repo secrets yet. That is a provisioning task, not a code bug; it flips to `xpass` once
`AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY` are set.
